### ISSUE TITLE
`yarn build` throws error

### ISSUE THREAD

**Issue by TimDaub** [spinamp/web3-music-subgraph#8]
```
Compile subgraphERROR TS6054: File 'src/shared/nft.ts' not found.

 import {upsertERC721} from '../shared/nft'
                            ~~~~~~~~~~~~~~~
 in src/noizd/NOIZD.ts(6,28)

✖ Failed to compile subgraph: Failed to compile data source mapping: 1 parse error(s)
Error: Failed to compile data source mapping: 1 parse error(s)
    at Compiler._compileDataSourceMapping (/root/web3-music-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:307:13)
    at /root/web3-music-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:216:20
    at updateInDeepMap (/root/web3-music-subgraph/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/root/web3-music-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/root/web3-music-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/root/web3-music-subgraph/node_modules/immutable/dist/immutable.js:1278:26)
    at /root/web3-music-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:215:24
    at /root/web3-music-subgraph/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/root/web3-music-subgraph/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/root/web3-music-subgraph/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/noizd/NOIZD.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
```

it seems the naming of `nft` isn't compatible with how it's named in the `import` statement

**Comment by TimDaub** [comment]
superseeded by #10
